### ISSUE TITLE
Implement Google Tag Manager Basic Model for TIKI SDK Initialization

### ISSUE THREAD

**Issue by ricardobrg** [tiki/website-home#127]
As a developer, I want to create a Google Tag Manager (GTM) model so that I can initialize the TIKI SDK for tracking and analytics purposes.

### Tasks
- [ ] Create a new Google Tag Manager container.
- [ ] Inject TIKI SDK JS Library and Initialize it
- [ ] Create a new Tag in the GTM container.
- [ ] Initialize the TIKI SDK using the provided publishingId, which should be obtained from GTM variables.
The user ID should be injected into the TIKI SDK either through the data layer or a custom JavaScript variable.

### Acceptance Criteria

- A new Tag is created in the GTM container.
- The Tag is configured to inject the TIKI SDK JavaScript library.
- The TIKI SDK is initialized using the publishingId obtained from GTM variables.
- The user ID is successfully injected into the TIKI SDK using the data layer or a custom JavaScript variable.

**Comment by ricardobrg** [comment]
not applicable
